Update cronjobs

diff --git a/cmd/cronjobs b/cmd/cronjobs
--- a/cmd/cronjobs
+++ b/cmd/cronjobs
@@ -45,6 +45,11 @@ while [[ "$#" -gt 0 ]]; do
       shift 2
       ;;
     -f|--function)
+    	if [[ -z "$2" || "$2" == -* ]]; then
+		      echo "Error: -f requires a valid function argument"
+		      exit 1
+		  fi
+
       FUNC="$2"
       shift 2
       ;;
@@ -52,7 +57,7 @@ while [[ "$#" -gt 0 ]]; do
       CONFIG_PATH="$2"
       shift 2
       ;;
-    -verbose|--verbose)
+    -v|--verbose)
       VERBOSE=true
       shift
       ;;
